# Generated by Django 5.0.14 on 2025-11-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Customer full name",
                        max_length=100,
                        verbose_name="Name",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Customer phone number",
                        max_length=20,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Customer email address",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Inquiry subject (optional)",
                        max_length=200,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Customer inquiry message", verbose_name="Message"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Product the customer is asking about (optional)",
                        max_length=200,
                        verbose_name="Product of Interest",
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("zh", "Traditional Chinese"),
                            ("en", "English"),
                            ("both", "Both Languages"),
                        ],
                        default="zh",
                        max_length=10,
                        verbose_name="Language Preference",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("replied", "Replied"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes for staff",
                        verbose_name="Admin Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the inquiry was replied to",
                        null=True,
                        verbose_name="Replied At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="contact_con_status_5380c0_idx",
                    ),
                    models.Index(fields=["email"], name="contact_con_email_343558_idx"),
                ],
            },
        ),
    ]
