# Generated by Django 5.0.14 on 2025-11-14 05:14

import apps.shop.models
import django.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        help_text="Company name in Traditional Chinese",
                        max_length=200,
                        verbose_name="Company Name (Chinese)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Company name in English",
                        max_length=200,
                        verbose_name="Company Name (English)",
                    ),
                ),
                (
                    "about_zh",
                    models.TextField(
                        help_text="Company story and description in Traditional Chinese",
                        verbose_name="About (Chinese)",
                    ),
                ),
                (
                    "about_en",
                    models.TextField(
                        help_text="Company story and description in English",
                        verbose_name="About (English)",
                    ),
                ),
                (
                    "address_zh",
                    models.TextField(
                        help_text="Physical address in Traditional Chinese",
                        verbose_name="Address (Chinese)",
                    ),
                ),
                (
                    "address_en",
                    models.TextField(
                        help_text="Physical address in English",
                        verbose_name="Address (English)",
                    ),
                ),
                (
                    "phone",
                    models.CharField(help_text="Primary phone number", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address", max_length=254
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Latitude coordinate for Google Maps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="Longitude coordinate for Google Maps",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "business_hours_zh",
                    models.TextField(
                        help_text="Operating hours in Traditional Chinese",
                        verbose_name="Business Hours (Chinese)",
                    ),
                ),
                (
                    "business_hours_en",
                    models.TextField(
                        help_text="Operating hours in English",
                        verbose_name="Business Hours (English)",
                    ),
                ),
                (
                    "line_id",
                    models.CharField(
                        blank=True,
                        help_text="LINE messenger ID",
                        max_length=100,
                        verbose_name="LINE ID",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp phone number",
                        max_length=20,
                        verbose_name="WhatsApp",
                    ),
                ),
                (
                    "facebook_url",
                    models.URLField(
                        blank=True,
                        help_text="Facebook page URL",
                        verbose_name="Facebook URL",
                    ),
                ),
                (
                    "hero_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        help_text="Main hero image for homepage and about page",
                        null=True,
                        upload_to=apps.shop.models.CompanyInfo.upload_to_company_images,
                        verbose_name="Hero Image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Information",
                "verbose_name_plural": "Company Information",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        help_text="Category name in Traditional Chinese",
                        max_length=100,
                        verbose_name="Name (Chinese)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Category name in English",
                        max_length=100,
                        verbose_name="Name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (lowercase, numbers, hyphens only)",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Slug must contain only lowercase letters, numbers, and hyphens.",
                                regex="^[a-z0-9-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "description_zh",
                    models.TextField(
                        blank=True,
                        help_text="Category description in Traditional Chinese",
                        verbose_name="Description (Chinese)",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Category description in English",
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Sort order for display (0 = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether category is visible to customers",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name_en"],
                "indexes": [
                    models.Index(
                        fields=["name_zh"], name="shop_catego_name_zh_8dbf99_idx"
                    ),
                    models.Index(
                        fields=["name_en"], name="shop_catego_name_en_307f2e_idx"
                    ),
                    models.Index(
                        fields=["display_order"], name="shop_catego_display_b55da7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(
                        help_text="Product name in Traditional Chinese",
                        max_length=200,
                        verbose_name="Name (Chinese)",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Product name in English",
                        max_length=200,
                        verbose_name="Name (English)",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "description_zh",
                    models.TextField(
                        help_text="Product description in Traditional Chinese",
                        verbose_name="Description (Chinese)",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Product description in English",
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in TWD (New Taiwan Dollar)",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="kg",
                        help_text="Unit of measurement (e.g., kg, piece, pack)",
                        max_length=50,
                    ),
                ),
                (
                    "weight_grams",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Weight per unit in grams (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "origin_zh",
                    models.CharField(
                        blank=True,
                        help_text="Product origin/source in Traditional Chinese",
                        max_length=200,
                        verbose_name="Origin (Chinese)",
                    ),
                ),
                (
                    "origin_en",
                    models.CharField(
                        blank=True,
                        help_text="Product origin/source in English",
                        max_length=200,
                        verbose_name="Origin (English)",
                    ),
                ),
                (
                    "nutritional_info_zh",
                    models.TextField(
                        blank=True,
                        help_text="Nutritional information in Traditional Chinese",
                        verbose_name="Nutritional Info (Chinese)",
                    ),
                ),
                (
                    "nutritional_info_en",
                    models.TextField(
                        blank=True,
                        help_text="Nutritional information in English",
                        verbose_name="Nutritional Info (English)",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this product should be featured on homepage",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this product is available for sale",
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("seasonal", "Seasonal"),
                        ],
                        default="in_stock",
                        help_text="Current stock status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "ordering": ["-is_featured", "name_en"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to=apps.shop.models.ProductImage.upload_to_product_images,
                        verbose_name="Image",
                    ),
                ),
                (
                    "alt_text_zh",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text in Traditional Chinese for accessibility",
                        max_length=200,
                        verbose_name="Alt Text (Chinese)",
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True,
                        help_text="Alternative text in English for accessibility",
                        max_length=200,
                        verbose_name="Alt Text (English)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order for displaying images (0 = first)"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary image for the product",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "ordering": ["display_order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name_zh"], name="shop_produc_name_zh_31174a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["name_en"], name="shop_produc_name_en_afe2f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_available"],
                name="shop_produc_categor_b360d9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured"], name="shop_produc_is_feat_e938b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["stock_status"], name="shop_produc_stock_s_02d156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "display_order"],
                name="shop_produc_product_18383c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["is_primary"], name="shop_produc_is_prim_61e92f_idx"
            ),
        ),
    ]
