# Generated by Django 5.0.14 on 2025-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                help_text="Instagram profile URL",
                verbose_name="Instagram URL",
            ),
        ),
    ]
